spring:
  application:
    name: user-statistics
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:walletapi}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      idle-timeout: 300000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml